-- Insert sample Ayurvedic products
INSERT INTO public.products (name, category, price, description, benefits, usage, certification, image_url, stock_quantity) VALUES
('Ashwagandha Powder', 'Supplements', 499.00, 'Pure organic Ashwagandha root powder for stress relief and immunity', ARRAY['Stress Relief', 'Improved Sleep', 'Enhanced Immunity', 'Mental Clarity'], 'Mix 1 teaspoon with warm milk daily', 'USDA Organic', '/ashwagandha.jpg', 50),
('Brahmi Hair Oil', 'Hair Care', 349.00, 'Traditional Brahmi oil for healthy hair growth and scalp nourishment', ARRAY['Hair Growth', 'Scalp Health', 'Shine Enhancement', 'Dandruff Control'], 'Apply to scalp 2-3 times weekly', 'ISO Certified', '/brahmi-oil.jpg', 30),
('Turmeric Curcumin', 'Supplements', 599.00, 'High-potency turmeric with black pepper for anti-inflammatory benefits', ARRAY['Anti-Inflammatory', 'Joint Health', 'Digestion Support', 'Antioxidant'], 'Take 1 capsule twice daily with food', 'GMP Certified', '/turmeric.jpg', 45),
('Neem Soap', 'Skin Care', 99.00, 'Natural neem soap for acne-prone and oily skin', ARRAY['Acne Control', 'Bacterial Control', 'Skin Purification', 'Natural Cleansing'], 'Use twice daily as regular soap', 'Dermatologist Tested', '/neem-soap.jpg', 100),
('Triphala Powder', 'Supplements', 349.00, 'Balanced blend of three fruits for digestive health', ARRAY['Digestive Health', 'Detoxification', 'Natural Cleansing', 'Energy Boost'], 'Mix 1 teaspoon with warm water at bedtime', 'USDA Organic', '/triphala.jpg', 40),
('Chyawanprash', 'Supplements', 599.00, 'Traditional immunity-boosting herbal jam', ARRAY['Immunity Boost', 'Respiratory Health', 'Energy', 'Vitality'], 'Take 1 spoon daily morning with milk', 'Ayurvedic Certified', '/chyawanprash.jpg', 35),
('Brahmi Ghee', 'Dairy Products', 749.00, 'Pure ghee infused with Brahmi herbs for brain health', ARRAY['Brain Health', 'Memory Enhancement', 'Cognitive Function', 'Pitta Balance'], 'Use in cooking or take 1 teaspoon daily', 'Pure & Unadulterated', '/brahmi-ghee.jpg', 25),
('Neem Neem Paste', 'Skin Care', 199.00, 'Neem leaf paste for skin infections and wounds', ARRAY['Wound Healing', 'Skin Infections', 'Anti-bacterial', 'Natural Antiseptic'], 'Apply directly to affected area', 'Natural Extract', '/neem-paste.jpg', 50),
('Shatavari Root', 'Supplements', 549.00, 'Women health and reproductive system support', ARRAY['Women Health', 'Hormonal Balance', 'Reproductive Health', 'Vitality'], 'Take 1 teaspoon with warm milk daily', 'Organic Certified', '/shatavari.jpg', 30);
