-- ========================================
-- MASTER CATALOGUE OVERHAUL - FINAL UPDATE
-- Complete product replacement with new official catalogue
-- ========================================

-- Step 1: Extend products table with new fields
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS form_type TEXT DEFAULT 'Capsules',
ADD COLUMN IF NOT EXISTS quantity_spec TEXT,
ADD COLUMN IF NOT EXISTS ingredients TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS seo_tags TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS storage_instructions TEXT,
ADD COLUMN IF NOT EXISTS dosage_instructions TEXT,
ADD COLUMN IF NOT EXISTS disclaimer TEXT;

-- Step 2: Clear existing products and kits (handle foreign keys)
DELETE FROM public.order_items WHERE product_id IN (SELECT id FROM public.products);
DELETE FROM public.products WHERE TRUE;
DELETE FROM public.health_kits WHERE TRUE;

-- Step 3: Insert new catalogue products (54 products across 13 categories)

-- BONE HEALTH (3 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('BoneCare Capsules', 'Bone Health', 699.00, 'Premium Ayurvedic bone strengthening formula supporting bone density and flexibility', ARRAY['Supports bone strength', 'Enhances bone flexibility', 'Promotes calcium absorption', 'Natural bone care'], 'Take 2 capsules daily after meals with water', 'Capsules', '60 capsules (500mg)', ARRAY['Calcium-rich herbs', 'Ashwagandha', 'Shatavari', 'Mineral complex'], ARRAY['strong bones', 'joint support', 'calcium capsules', 'ayurvedic bone care', 'bone health'], 'Store in cool, dry place away from moisture. Keep away from sunlight.', '2 capsules, 2x daily after meals', '/catalogue/bone-care-capsules.jpg', 100, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('Bone Gummies', 'Bone Health', 549.00, 'Delicious herbal gummies for bone health with natural calcium and vitamin D support', ARRAY['Supports bone strength', 'Tasty & easy to consume', 'Calcium enriched', 'Vegetarian formula'], '1-2 gummies daily, chew well before swallowing', 'Gummies', '60 gummies', ARRAY['Calcium citrate', 'Vitamin D3', 'Ashwagandha', 'Natural flavors'], ARRAY['bone gummies', 'calcium gummies', 'bone support', 'vegan gummies', 'bone health'], 'Store in cool, dry place. Close container tightly after use.', '1-2 gummies daily', '/catalogue/bone-gummies.jpg', 80, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('Bone Oil', 'Bone Health', 799.00, 'Potent Ayurvedic massage oil for joint and bone health with warming properties', ARRAY['Supports joint flexibility', 'Warming effect', 'Reduces stiffness', 'Nourishes bones'], 'Apply and massage gently on affected areas 2-3 times daily', 'Oil', '100 ml', ARRAY['Sesame oil', 'Turmeric', 'Ginger', 'Eucalyptus'], ARRAY['bone oil', 'joint oil', 'arthritis oil', 'massage oil', 'bone care'], 'Keep in cool place. Shake before use. Use within 6 months of opening.', 'Massage 10-15 ml, 2-3x daily', '/catalogue/bone-oil.jpg', 60, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- DETOX & LIVER SUPPORT (4 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('LiverClean Syrup', 'Detox & Liver Support', 549.00, 'Herbal syrup to support liver cleansing and detoxification naturally', ARRAY['Supports liver cleansing', 'Promotes detoxification', 'Improves liver function', 'Natural ingredients'], 'Take 1-2 teaspoons twice daily after meals with water', 'Syrup', '200 ml', ARRAY['Kutki', 'Kalmegh', 'Giloy', 'Bhringraj'], ARRAY['liver detox syrup', 'liver cleanse', 'natural detox', 'ayurvedic liver', 'liver health'], 'Store in cool place. Refrigerate after opening. Use within 2 months.', '1-2 tsp, 2x daily after meals', '/catalogue/liver-clean-syrup.jpg', 90, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('LiverGuard Capsules', 'Detox & Liver Support', 799.00, 'Premium liver support formula with potent hepatoprotective herbs', ARRAY['Protects liver health', 'Supports detoxification', 'Improves liver function', 'Natural herbs'], 'Take 1-2 capsules twice daily with meals', 'Capsules', '60 capsules', ARRAY['Milk Thistle', 'Kutki', 'Kalmegh', 'Bhringraj'], ARRAY['liver support capsules', 'hepatoprotective', 'liver health', 'detox supplement', 'liver care'], 'Store in dry place away from heat and moisture.', '1-2 capsules, 2x daily with meals', '/catalogue/liver-guard-capsules.jpg', 75, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('DetoxFizz', 'Detox & Liver Support', 399.00, 'Refreshing detox formula in convenient effervescent tablet form for daily cleansing', ARRAY['Easy daily detox', 'Supports liver', 'Refreshing taste', 'Quick absorption'], '1 tablet dissolved in water once or twice daily', 'Effervescent Tablets', '30 tablets', ARRAY['Amla', 'Turmeric', 'Ginger', 'Lemon extract'], ARRAY['detox effervescent', 'fizz tablets', 'detox drink', 'liver cleanse', 'daily detox'], 'Keep in dry place. Close container tightly after use.', '1 tablet in water, 1-2x daily', '/catalogue/detox-fizz.jpg', 110, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('Liver & Detox Juice', 'Detox & Liver Support', 649.00, 'Fresh herbal juice blend for liver support with Kutki, Kalmegh, Giloy, and Aloe Vera', ARRAY['Natural liver detox', 'Supports cleansing', 'Rich in antioxidants', 'Improves digestion'], 'Take 30-60 ml twice daily before meals', 'Juice', '500 ml', ARRAY['Kutki', 'Kalmegh', 'Giloy', 'Aloe Vera'], ARRAY['detox juice', 'liver juice', 'cleanse juice', 'herbal juice', 'detoxification'], 'Refrigerate after opening. Use within 4 weeks of opening.', '30-60 ml, 2x daily before meals', '/catalogue/liver-detox-juice.jpg', 50, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- DIGESTION SUPPORT (4 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('DigestEase Powder', 'Digestion Support', 449.00, 'Traditional digestive powder to support healthy digestion and reduce bloating', ARRAY['Supports healthy digestion', 'Reduces bloating', 'Eases gas and acidity', 'Improves nutrient absorption'], 'Mix 1/2 teaspoon with warm water after meals', 'Churna (Powder)', '150 g', ARRAY['Ajwain', 'Ginger', 'Fennel', 'Cumin'], ARRAY['digestive powder', 'churna', 'ayurvedic digestion', 'bloating relief', 'gut health'], 'Store in airtight container in cool, dry place.', '1/2 tsp in warm water, after meals', '/catalogue/digest-ease-powder.jpg', 95, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('GutBalance Capsules', 'Digestion Support', 649.00, 'Probiotic-friendly capsules to restore gut balance and improve digestion', ARRAY['Restores gut balance', 'Improves digestion', 'Reduces IBS symptoms', 'Enhances nutrient absorption'], 'Take 1-2 capsules daily with meals', 'Capsules', '60 capsules', ARRAY['Fennel', 'Ginger', 'Triphala', 'Psyllium husk'], ARRAY['gut health capsules', 'probiotic capsules', 'digestive health', 'IBS relief', 'gut flora'], 'Store in cool, dry place away from direct sunlight.', '1-2 capsules daily with meals', '/catalogue/gut-balance-capsules.jpg', 85, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('DigestOil', 'Digestion Support', 399.00, 'Warming massage oil infused with digestive herbs for abdominal health', ARRAY['Supports digestion', 'Reduces gas and bloating', 'Warming effect', 'Eases discomfort'], 'Massage 5-10 ml gently on abdomen in clockwise motion after meals', 'Oil', '50 ml', ARRAY['Sesame oil', 'Fennel', 'Ginger', 'Cumin'], ARRAY['digestive oil', 'stomach oil', 'massage oil', 'digestive support', 'abdominal health'], 'Store in cool place. Keep container tightly sealed.', 'Massage 5-10 ml on abdomen, 1-2x daily', '/catalogue/digest-oil.jpg', 70, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('Digestive Support Juice', 'Digestion Support', 699.00, 'Fresh juice blend for digestive wellness with Amla, Ginger, Fennel, and Triphala', ARRAY['Supports healthy digestion', 'Improves bowel movement', 'Rich in antioxidants', 'Natural cleansing'], 'Take 30-60 ml before meals once or twice daily', 'Juice', '500 ml', ARRAY['Amla', 'Ginger', 'Fennel', 'Triphala'], ARRAY['digestive juice', 'detox juice', 'gut health juice', 'herbal juice', 'ayurvedic digestion'], 'Refrigerate after opening. Use within 4 weeks.', '30-60 ml, 1-2x daily before meals', '/catalogue/digestive-support-juice.jpg', 60, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- GOUT CARE (3 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('GoutRelief Capsules', 'Gout Care', 749.00, 'Specialized formula for gout relief with uric acid management support', ARRAY['Reduces uric acid', 'Relieves gout pain', 'Supports joint health', 'Prevents inflammation'], 'Take 1-2 capsules twice daily with meals', 'Capsules', '60 capsules', ARRAY['Neem', 'Turmeric', 'Ginger', 'Punarnava'], ARRAY['gout relief capsules', 'uric acid reduction', 'gout treatment', 'joint health', 'anti-inflammatory'], 'Store in dry place away from moisture.', '1-2 capsules, 2x daily with meals', '/catalogue/gout-relief-capsules.jpg', 65, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('UricDown Powder', 'Gout Care', 599.00, 'Herbal powder to help reduce elevated uric acid levels naturally', ARRAY['Reduces uric acid levels', 'Supports gout prevention', 'Eases joint discomfort', 'Natural detox support'], 'Mix 1 teaspoon with warm water twice daily after meals', 'Churna (Powder)', '200 g', ARRAY['Varuna', 'Punarnava', 'Chirayta', 'Ginger'], ARRAY['uric acid powder', 'gout prevention', 'herbal detox', 'ayurvedic gout care', 'uric acid management'], 'Store in airtight container in cool place.', '1 tsp in warm water, 2x daily after meals', '/catalogue/uric-down-powder.jpg', 55, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('GoutRelief Oil', 'Gout Care', 549.00, 'Therapeutic massage oil for gout-affected joints with warming and anti-inflammatory properties', ARRAY['Relieves gout pain', 'Reduces inflammation', 'Improves circulation', 'Warming effect'], 'Massage 10-15 ml gently on affected joints 2-3 times daily', 'Oil', '100 ml', ARRAY['Sesame oil', 'Turmeric', 'Ginger', 'Camphor'], ARRAY['gout oil', 'joint relief oil', 'massage oil', 'anti-inflammatory oil', 'pain relief'], 'Store in cool place. Avoid direct sunlight. Close tightly after use.', 'Massage 10-15 ml on joints, 2-3x daily', '/catalogue/gout-relief-oil.jpg', 50, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- HAIR CARE (4 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('HairVital Shampoo', 'Hair Care', 449.00, 'Gentle herbal shampoo for nourished scalp and strong, healthy hair', ARRAY['Strengthens hair', 'Promotes growth', 'Nourishes scalp', 'Reduces dandruff'], 'Apply to wet hair, lather and rinse thoroughly. Use 2-3 times weekly', 'Shampoo', '200 ml', ARRAY['Neem', 'Hibiscus', 'Shikakai', 'Brahmi'], ARRAY['herbal shampoo', 'hair care shampoo', 'anti-dandruff', 'hair growth', 'natural shampoo'], 'Store in cool place. Close bottle tightly after use.', 'Use 2-3 times weekly for best results', '/catalogue/hair-vital-shampoo.jpg', 100, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('HairGrowth Oil', 'Hair Care', 599.00, 'Potent herbal oil blend specifically formulated to promote hair growth and reduce hair fall', ARRAY['Promotes hair growth', 'Reduces hair fall', 'Nourishes follicles', 'Adds shine'], 'Apply warm oil to scalp and hair. Leave for 30 minutes or overnight. Wash with shampoo', 'Oil', '100 ml', ARRAY['Sesame oil', 'Brahmi', 'Bhringraj', 'Neem'], ARRAY['hair growth oil', 'anti-hair fall', 'scalp oil', 'ayurvedic hair oil', 'hair nourishment'], 'Store in cool place away from direct heat. Close tightly after use.', 'Apply warm oil, leave 30 min to overnight, 2x weekly', '/catalogue/hair-growth-oil.jpg', 85, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('HairVital Gummies', 'Hair Care', 499.00, 'Delicious herbal gummies for hair health and growth from within', ARRAY['Promotes hair growth', 'Reduces hair fall', 'Improves hair texture', 'Vegetarian'], 'Chew 1-2 gummies daily for best results', 'Gummies', '60 gummies', ARRAY['Biotin', 'Amla', 'Brahmi', 'Natural flavors'], ARRAY['hair gummies', 'biotin gummies', 'hair growth supplement', 'hair health', 'vegan gummies'], 'Store in cool place. Close container tightly. Use within 6 months.', '1-2 gummies daily', '/catalogue/hair-vital-gummies.jpg', 70, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('Hair Serum', 'Hair Care', 749.00, 'Premium hair serum with Argan Oil, Aloe Vera, and Vitamin E for strong, lustrous hair', ARRAY['Strengthens hair', 'Adds shine and smoothness', 'Reduces frizz', 'Protects from damage'], 'Apply 2-3 drops to damp hair and style as usual. Can be used daily', 'Serum', '50 ml', ARRAY['Argan Oil', 'Aloe Vera', 'Vitamin E', 'Jojoba Oil'], ARRAY['hair serum', 'argan oil serum', 'frizz control', 'hair shine', 'hair treatment'], 'Store away from direct sunlight. Keep container tightly closed.', '2-3 drops to damp hair, daily or as needed', '/catalogue/hair-serum.jpg', 45, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- IMMUNITY SUPPORT (4 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('ImmunoBoost Gummies', 'Immunity Support', 549.00, 'Tasty immunity-boosting gummies with natural herbs and vitamin C for daily protection', ARRAY['Boosts immunity', 'Rich in Vitamin C', 'Easy to consume', 'Natural ingredients'], 'Take 1-2 gummies daily or as directed', 'Gummies', '60 gummies', ARRAY['Amla', 'Tulsi', 'Vitamin C', 'Natural flavors'], ARRAY['immunity gummies', 'vitamin c gummies', 'immune support', 'antioxidant gummies', 'health gummies'], 'Store in cool place. Close container tightly. Use within 6 months of opening.', '1-2 gummies daily', '/catalogue/immunoboost-gummies.jpg', 90, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('ImmunoPlus Capsules', 'Immunity Support', 699.00, 'Comprehensive immune support formula with powerful Ayurvedic herbs', ARRAY['Strengthens immunity', 'Fights infections', 'Antioxidant rich', 'Natural protection'], 'Take 1-2 capsules daily with meals or as directed', 'Capsules', '60 capsules', ARRAY['Ashwagandha', 'Tulsi', 'Giloy', 'Amla'], ARRAY['immunity capsules', 'immune support', 'antioxidant capsules', 'ayurvedic immunity', 'infection fighter'], 'Store in dry place away from moisture and heat.', '1-2 capsules daily with meals', '/catalogue/immunoplus-capsules.jpg', 80, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('ImmunoShield Syrup', 'Immunity Support', 449.00, 'Herbal syrup to strengthen immunity and protect against seasonal infections', ARRAY['Boosts immunity', 'Protects from infections', 'Rich in antioxidants', 'Easy to take'], 'Take 1-2 teaspoons twice daily with water or milk', 'Syrup', '200 ml', ARRAY['Tulsi', 'Ashwagandha', 'Giloy', 'Honey'], ARRAY['immunity syrup', 'immunoprotective', 'infection prevention', 'herbal syrup', 'immune booster'], 'Store in cool place. Refrigerate after opening. Use within 2 months.', '1-2 tsp, 2x daily with water or milk', '/catalogue/immunoshield-syrup.jpg', 75, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('Immunity Booster Juice', 'Immunity Support', 749.00, 'Fresh immunity-boosting juice blend for daily protection and wellness', ARRAY['Boosts natural immunity', 'Rich in Vitamin C', 'Daily protection', 'Supports wellness'], 'Take 30-60 ml twice daily before meals', 'Juice', '500 ml', ARRAY['Amla', 'Tulsi', 'Ginger', 'Lemon'], ARRAY['immunity juice', 'vitamin c juice', 'antioxidant juice', 'health juice', 'natural immunity'], 'Refrigerate after opening. Use within 4 weeks of opening.', '30-60 ml, 2x daily before meals', '/catalogue/immunity-booster-juice.jpg', 65, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- JOINT CARE (3 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('ArthroFlex Oil', 'Joint Care', 699.00, 'Therapeutic joint oil for flexibility and comfortable movement with warming properties', ARRAY['Improves flexibility', 'Supports joint health', 'Reduces stiffness', 'Warming effect'], 'Massage 10-15 ml on affected joints 2-3 times daily', 'Oil', '100 ml', ARRAY['Sesame oil', 'Turmeric', 'Ginger', 'Eucalyptus'], ARRAY['joint oil', 'arthritis relief', 'flexibility oil', 'massage oil', 'joint care'], 'Store in cool place away from sunlight. Keep container tightly sealed.', 'Massage 10-15 ml on joints, 2-3x daily', '/catalogue/arthro-flex-oil.jpg', 70, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('ArthroRelief Cream', 'Joint Care', 599.00, 'Soothing topical cream for joint and muscle discomfort with herbs', ARRAY['Relieves joint discomfort', 'Reduces inflammation', 'Soothing effect', 'Easy application'], 'Apply and massage gently on affected areas 2-3 times daily', 'Cream', '50 g', ARRAY['Turmeric', 'Ginger', 'Eucalyptus', 'Camphor'], ARRAY['joint cream', 'arthritis cream', 'relief cream', 'topical cream', 'muscle relief'], 'Store in cool place. Keep container tightly closed after use.', 'Apply and massage, 2-3x daily as needed', '/catalogue/arthro-relief-cream.jpg', 55, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('JointFlex Gummies', 'Joint Care', 649.00, 'Herbal gummies for joint flexibility and mobility support', ARRAY['Supports joint flexibility', 'Easy to consume', 'Natural ingredients', 'Vegetarian'], 'Take 1-2 gummies daily for best results', 'Gummies', '60 gummies', ARRAY['Ginger', 'Turmeric', 'Boswellia', 'Natural flavors'], ARRAY['joint gummies', 'flexibility gummies', 'joint health', 'mobility support', 'herbal gummies'], 'Store in cool place. Close container tightly after use.', '1-2 gummies daily', '/catalogue/joint-flex-gummies.jpg', 60, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- MEN'S HEALTH (2 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('VitoHerb Capsules', 'Mens Health', 899.00, 'Premium formulation for mens vitality, stamina, and overall wellness', ARRAY['Boosts stamina', 'Enhances vitality', 'Supports performance', 'Natural strength'], 'Take 1-2 capsules daily with meals', 'Capsules', '60 capsules', ARRAY['Safed Musli', 'Ashwagandha', 'Gokshura', 'Shilajit'], ARRAY['mens health', 'vitality capsules', 'stamina supplement', 'performance support', 'ayurvedic mens health'], 'Store in dry place away from heat and moisture.', '1-2 capsules daily with meals', '/catalogue/vito-herb-capsules.jpg', 50, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('PowerFizz', 'Mens Health', 449.00, 'Refreshing energy and stamina-boosting effervescent tablets for men', ARRAY['Boosts energy', 'Supports stamina', 'Refreshing taste', 'Quick absorption'], '1 tablet dissolved in water once daily', 'Effervescent Tablets', '30 tablets', ARRAY['Ginseng', 'Ashwagandha', 'Ginger', 'Lemon extract'], ARRAY['energy tablets', 'stamina fizz', 'men energy', 'sports nutrition', 'vitality'], 'Keep in dry place. Close container tightly after use.', '1 tablet in water, once daily', '/catalogue/power-fizz.jpg', 65, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- MIGRAINE SUPPORT (3 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('MigraEase Tablets', 'Migraine Support', 449.00, 'Quick relief tablets for migraine discomfort and tension headaches', ARRAY['Relieves migraine pain', 'Reduces tension', 'Fast-acting', 'Natural formula'], 'Take 1-2 tablets with water at onset of migraine, repeat after 4-6 hours if needed', 'Tablets', '30 tablets', ARRAY['Feverfew', 'Ginger', 'Brahmi', 'Turmeric'], ARRAY['migraine tablets', 'headache relief', 'tension headache', 'natural pain relief', 'migraine support'], 'Store in cool, dry place in airtight container.', '1-2 tablets with water, as needed', '/catalogue/migra-ease-tablets.jpg', 80, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('MigraEase Capsules', 'Migraine Support', 599.00, 'Comprehensive migraine support capsules for prevention and relief', ARRAY['Prevents migraines', 'Reduces frequency', 'Eases symptoms', 'Long-term support'], 'Take 1 capsule daily with meals for prevention, 2 capsules at migraine onset', 'Capsules', '60 capsules', ARRAY['Feverfew', 'Brahmi', 'Ginger', 'Turmeric'], ARRAY['migraine capsules', 'headache prevention', 'preventive supplement', 'herbal relief', 'migraine management'], 'Store in cool, dry place away from moisture.', '1-2 capsules daily with meals', '/catalogue/migra-ease-capsules.jpg', 70, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('MigraCalm Roll-on', 'Migraine Support', 349.00, 'Portable roll-on oil for quick relief and comfort during migraines', ARRAY['Quick relief', 'Portable format', 'Easy application', 'Soothing effect'], 'Roll on temples, forehead and nape during migraine. Can repeat every 2-3 hours', 'Roll-on Oil', '10 ml', ARRAY['Peppermint oil', 'Eucalyptus', 'Lavender', 'Brahmi'], ARRAY['migraine roll-on', 'headache relief oil', 'portable relief', 'temple oil', 'migraine comfort'], 'Keep upright. Store in cool place away from direct sunlight.', 'Apply to temples/forehead, repeat every 2-3 hours as needed', '/catalogue/migra-calm-roll-on.jpg', 100, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- SKIN CARE (3 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('GlowHerb Cream', 'Skin Care', 649.00, 'Nourishing skin cream for glow, radiance, and natural beauty', ARRAY['Promotes skin glow', 'Nourishes deeply', 'Anti-aging properties', 'Natural radiance'], 'Apply gently on clean face and neck morning and night', 'Cream', '50 g', ARRAY['Turmeric', 'Sandalwood', 'Aloe Vera', 'Coconut oil'], ARRAY['skin glow cream', 'face cream', 'nourishing cream', 'anti-aging', 'natural skincare'], 'Store in cool place away from direct sunlight.', 'Apply morning and night to clean skin', '/catalogue/glow-herb-cream.jpg', 75, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('AcneClear Face Wash', 'Skin Care', 349.00, 'Gentle yet effective face wash for acne-prone skin and prevention', ARRAY['Controls acne', 'Purifies pores', 'Anti-bacterial', 'Natural cleansing'], 'Wet face, apply wash, massage gently for 1-2 minutes, rinse well. Use twice daily', 'Face Wash', '100 ml', ARRAY['Neem', 'Tea Tree', 'Turmeric', 'Salicylic acid alternative'], ARRAY['acne face wash', 'anti-acne', 'face cleanser', 'pore purifier', 'natural face wash'], 'Store in cool place. Keep container tightly closed.', 'Use twice daily for best results', '/catalogue/acne-clear-face-wash.jpg', 110, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('SkinGlow Capsules', 'Skin Care', 749.00, 'Internal beauty support capsules for radiant and healthy skin', ARRAY['Promotes skin radiance', 'Anti-oxidant rich', 'Supports collagen', 'Natural glow'], 'Take 1-2 capsules daily with meals', 'Capsules', '60 capsules', ARRAY['Turmeric', 'Saffron', 'Brahmi', 'Vitamin C'], ARRAY['skin glow capsules', 'beauty supplement', 'anti-oxidant', 'skin health', 'natural beauty'], 'Store in cool, dry place away from moisture.', '1-2 capsules daily with meals', '/catalogue/skin-glow-capsules.jpg', 60, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- STRESS MANAGEMENT (3 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('CalmMind Capsules', 'Stress Management', 699.00, 'Powerful stress relief formula for calm mind and emotional balance', ARRAY['Reduces stress', 'Promotes relaxation', 'Supports mental clarity', 'Emotional balance'], 'Take 1-2 capsules daily with meals or as directed', 'Capsules', '60 capsules', ARRAY['Brahmi', 'Ashwagandha', 'Jatamansi', 'Shankhpushpi'], ARRAY['stress relief capsules', 'anxiety relief', 'calm mind', 'mental health', 'ayurvedic stress'], 'Store in cool, dry place away from direct sunlight.', '1-2 capsules daily with meals', '/catalogue/calm-mind-capsules.jpg', 85, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('SleepWell Gummies', 'Stress Management', 549.00, 'Natural sleep support gummies for restful and peaceful sleep', ARRAY['Promotes sleep', 'Reduces stress', 'Calming effect', 'Restful rest'], 'Take 1-2 gummies 30 minutes before bedtime', 'Gummies', '60 gummies', ARRAY['Brahmi', 'Passionflower', 'Valerian', 'Natural flavors'], ARRAY['sleep gummies', 'natural sleep aid', 'insomnia relief', 'stress relief', 'sleep support'], 'Store in cool place. Close container tightly.', '1-2 gummies, 30 min before bed', '/catalogue/sleep-well-gummies.jpg', 90, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('CalmMind Head Oil', 'Stress Management', 499.00, 'Soothing head massage oil for stress relief and mental relaxation', ARRAY['Relieves stress', 'Soothes mind', 'Promotes relaxation', 'Healing effect'], 'Massage 10-15 ml on scalp and temples for 10-15 minutes daily', 'Oil', '100 ml', ARRAY['Sesame oil', 'Brahmi', 'Lavender', 'Jatamansi'], ARRAY['head oil', 'stress relief oil', 'massage oil', 'relaxation oil', 'mental peace'], 'Store in cool place. Keep container tightly sealed.', 'Massage 10-15 ml on scalp, daily or as needed', '/catalogue/calm-mind-head-oil.jpg', 70, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- WEIGHT MANAGEMENT (6 products)
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('TrimHerb Tablets', 'Weight Management', 449.00, 'Natural weight management tablets for healthy body weight and metabolism', ARRAY['Supports healthy weight', 'Boosts metabolism', 'Reduces cravings', 'Natural formula'], 'Take 1-2 tablets twice daily with meals', 'Tablets', '30 tablets', ARRAY['Garcinia', 'Ginger', 'Fenugreek', 'Guggul'], ARRAY['weight loss tablets', 'metabolism support', 'natural weight', 'herbal diet', 'obesity relief'], 'Store in dry place in airtight container.', '1-2 tablets, 2x daily with meals', '/catalogue/trim-herb-tablets.jpg', 75, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('FatBurn Capsules', 'Weight Management', 749.00, 'Advanced fat-burning formula for metabolism enhancement and weight management', ARRAY['Enhances fat burning', 'Supports metabolism', 'Improves digestion', 'Energy support'], 'Take 1-2 capsules daily with meals', 'Capsules', '60 capsules', ARRAY['Green Tea Extract', 'Garcinia', 'Ginger', 'Fenugreek'], ARRAY['fat burn capsules', 'weight loss supplement', 'metabolism', 'thermogenic', 'obesity management'], 'Store in cool, dry place away from moisture.', '1-2 capsules daily with meals', '/catalogue/fat-burn-capsules.jpg', 65, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('SlimTea Powder', 'Weight Management', 399.00, 'Refreshing herbal tea powder for weight management and daily wellness', ARRAY['Supports weight loss', 'Improves digestion', 'Refreshing taste', 'Metabolism boost'], 'Mix 1 teaspoon in hot water, drink twice daily, preferably morning and evening', 'Tea Powder', '100 g', ARRAY['Green Tea', 'Ginger', 'Cinnamon', 'Turmeric'], ARRAY['slim tea', 'weight loss tea', 'herbal tea', 'diet tea', 'metabolism tea'], 'Store in airtight container in cool place.', '1 tsp in hot water, 2x daily', '/catalogue/slim-tea-powder.jpg', 80, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('SlimDetox Powder', 'Weight Management', 449.00, 'Detoxifying powder to support weight loss and body cleansing', ARRAY['Detoxifies body', 'Supports weight loss', 'Improves digestion', 'Metabolism support'], 'Mix 1/2 teaspoon with warm water once or twice daily', 'Churna (Powder)', '150 g', ARRAY['Triphala', 'Ginger', 'Guggul', 'Haritaki'], ARRAY['detox powder', 'weight loss churna', 'body cleanse', 'metabolism powder', 'natural detox'], 'Store in airtight container in cool, dry place.', '1/2 tsp with warm water, 1-2x daily', '/catalogue/slim-detox-powder.jpg', 70, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('MetaboBoost Gummies', 'Weight Management', 599.00, 'Metabolism-boosting gummies for natural and sustainable weight management', ARRAY['Boosts metabolism', 'Supports weight loss', 'Energy support', 'Vegetarian'], 'Take 2 gummies daily with meals', 'Gummies', '60 gummies', ARRAY['Green Tea Extract', 'Garcinia', 'Biotin', 'Natural flavors'], ARRAY['metabolism gummies', 'weight loss gummies', 'energy gummies', 'natural metabolism', 'diet gummies'], 'Store in cool place. Close container tightly after use.', '2 gummies daily with meals', '/catalogue/metabo-boost-gummies.jpg', 60, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('Weight Loss Juice', 'Weight Management', 699.00, 'Fresh weight loss juice for natural and healthy weight management', ARRAY['Supports weight loss', 'Detoxifies body', 'Improves metabolism', 'Natural cleansing'], 'Take 30-60 ml once or twice daily before meals', 'Juice', '500 ml', ARRAY['Amla', 'Ginger', 'Lemon', 'Aloe Vera'], ARRAY['weight loss juice', 'detox juice', 'slimming juice', 'herbal juice', 'natural weight loss'], 'Refrigerate after opening. Use within 4 weeks.', '30-60 ml, 1-2x daily before meals', '/catalogue/weight-loss-juice.jpg', 55, TRUE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- WOMEN'S HEALTH (2 products)  
INSERT INTO public.products (name, category, price, description, benefits, usage, form_type, quantity_spec, ingredients, seo_tags, storage_instructions, dosage_instructions, image_url, stock_quantity, featured, certification, disclaimer) VALUES
('ShatiHerb Capsules', 'Womens Health', 799.00, 'Specialized formula for womens wellness, hormonal balance, and vitality', ARRAY['Supports womens health', 'Hormonal balance', 'Enhances vitality', 'Natural wellness'], 'Take 1-2 capsules daily with meals', 'Capsules', '60 capsules', ARRAY['Shatavari', 'Ashwagandha', 'Lodhra', 'Manjistha'], ARRAY['womens health', 'hormonal balance', 'womens wellness', 'ayurvedic women', 'female health'], 'Store in cool, dry place away from heat and moisture.', '1-2 capsules daily with meals', '/catalogue/shati-herb-capsules.jpg', 60, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.'),
('Women Vitality Gummies', 'Womens Health', 649.00, 'Nourishing gummies for womens health, energy, and wellness', ARRAY['Supports womens vitality', 'Energy support', 'Hormonal wellness', 'Vegetarian'], 'Take 2 gummies daily with meals for best results', 'Gummies', '60 gummies', ARRAY['Shatavari', 'Iron-rich herbs', 'Vitamin B12', 'Natural flavors'], ARRAY['women gummies', 'vitality gummies', 'energy gummies', 'womens health', 'herbal gummies'], 'Store in cool place. Close container tightly. Use within 6 months.', '2 gummies daily with meals', '/catalogue/women-vitality-gummies.jpg', 50, FALSE, 'ISO 9001:2015 Certified', 'These statements have not been evaluated by regulatory authorities. This product is not intended to diagnose, treat, cure or prevent any disease.');

-- Mark featured products
UPDATE public.products SET featured = TRUE WHERE name IN (
  'BoneCare Capsules',
  'DetoxFizz',
  'Liver & Detox Juice',
  'Digestive Support Juice',
  'HairGrowth Oil',
  'Hair Serum',
  'Immunity Booster Juice',
  'SkinGlow Capsules',
  'CalmMind Capsules',
  'Weight Loss Juice'
);

COMMIT;
